export let cryptocurrency = [
  {name: 'Bitcoin', symbol: 'BTCUSD', live: 'BTCUSDT', icon: 'btc', thumb: 'bitcoin.jpg'},
  {name: 'Ethereum', symbol: 'ETHUSD', live: 'ETHUSDT', icon: 'eth', thumb: 'ethereum.png'},
  {name: 'BNB', symbol: 'BNBUSD', live: 'BNBUSDT', icon: 'bnb', thumb: 'bnb.png'},
  {name: 'Cardano', symbol: 'ADAUSD', live: 'ADAUSDT', icon: 'ada', thumb: 'cardano.jpg'},
  {name: 'Solana', symbol: 'SOLUSD', live: 'SOLUSDT', icon: 'sol', thumb: 'sol.png'},
  {name: 'XRP', symbol: 'XRPUSD', live: 'XRPUSDT', icon: 'xrp', thumb: 'xrp.png'},
  {name: 'Polkadot', symbol: 'DOTUSD', live: 'DOTUSDT', icon: 'dot', thumb: 'polkadot.png'},
  {name: 'Dogecoin', symbol: 'DOGEUSD', live: 'DOGEUSDT', icon: 'doge', thumb: 'doge.jpg'},
  {name: 'Shiba Inu', symbol: 'SHIBUSD', live: 'SHIBUSDT', icon: 'shib', thumb: 'shiba.png'},
  {name: 'Terra', symbol: 'LUNAUSD', live: 'LUNAUSDT', icon: 'luna', thumb: 'luna.png'},
  {name: 'Avalanche', symbol: 'AVAXUSD', live: 'AVAXUSDT', icon: 'avax', thumb: 'avax.png'},
  {name: 'Litecoin', symbol: 'LTCUSD', live: 'LTCUSDT', icon: 'ltc', thumb: 'ltc.png'},
  {name: 'Uniswap', symbol: 'UNIUSD', live: 'UNIUSDT', icon: 'uni', thumb: 'uni.png'},
  {name: 'Chainlink', symbol: 'LINKUSD', live: 'LINKUSDT', icon: 'link', thumb: 'link.png'},
  {name: 'Polygon', symbol: 'MATICUSD', live: 'MATICUSDT', icon: 'matic', thumb: 'matic.png'},
  {name: 'Algorand', symbol: 'ALGOUSD', live: 'ALGOUSDT', icon: 'algo', thumb: 'algo.png'},
  {name: 'VeChain', symbol: 'VETUSD', live: 'VETUSDT', icon: 'vet', thumb: 'vet.png'},
  {name: 'Stellar', symbol: 'XLMUSD', live: 'XLMUSDT', icon: 'xlm', thumb: 'xlm.png'},
  {name: 'Axie Infinity', symbol: 'AXSUSD', live: 'AXSUSDT', icon: 'axs', thumb: 'axie.png'},
  {name: 'Filecoin', symbol: 'FILUSD', live: 'FILUSDT', icon: 'fil', thumb: 'file.png'},
  {name: 'TRON', symbol: 'TRXUSD', live: 'TRXUSDT', icon: 'trx', thumb: 'tron.png'},
  {name: 'Ethereum Classic', symbol: 'ETCUSD', live: 'ETCUSDT', icon: 'etc', thumb: 'etc.png'},
  {name: 'Cosmos', symbol: 'ATOMUSD', live: 'ATOMUSDT', icon: 'atom', thumb: 'atom.png'},
  {name: 'THETsansA', symbol: 'THETAUSD', live: 'HETAUSDT', icon: 'theta', thumb: 'theta.png'},
  {name: 'FTX Token', symbol: 'FTTUSD', live: 'FTTUSDT', icon: 'ftt', thumb: 'ftt.png'},
  {name: 'Fantom', symbol: 'FTMUSD', live: 'FTMUSDT', icon: 'ftm', thumb: 'ftm.png'},
  {name: 'Hedera', symbol: 'HBARUSD', live: 'HBARUSDT', icon: 'hbar', thumb: 'hbar.png'},
  {name: 'Dai', symbol: 'DAIUSD', live: 'DAIUSDT', icon: 'dai', thumb: 'dai.png'},
  {name: 'Elrond', symbol: 'EGLDUSD', live: 'EGLDUSDT', icon: 'egld', thumb: 'egld.png'},
  {name: 'NEAR Protocol', symbol: 'NEARUSD', live: 'NEARUSDT', icon: 'near', thumb: 'near.png'},
  {name: 'The Graph', symbol: 'GRTUSD', live: 'GRTUSDT', icon: 'grt', thumb: 'grt.png'},
  {name: 'Tezos', symbol: 'XTZUSD', live: 'XTZUSDT', icon: 'xtz', thumb: 'xtz.png'},
  {name: 'Monero', symbol: 'XMRUSD', live: 'XMRUSDT', icon: 'xmr', thumb: 'xmr.png'},
  {name: 'EOS', symbol: 'EOSUSD', live: 'EOSUSDT', icon: 'eos', thumb: 'eos.png'},
  {name: 'Decentraland', symbol: 'MANAUSD', live: 'MANAUSDT', icon: 'mana', thumb: 'mana.png'},
  {name: 'Helium', symbol: 'HNTUSD', live: 'HNTUSDT', icon: 'hnt', thumb: 'hnt.png'},
  {name: 'PancakeSwap', symbol: 'CAKEUSD', live: 'CAKEUSDT', icon: 'cake', thumb: 'cake.png'},
  {name: 'Aave', symbol: 'AAVEUSD', live: 'AAVEUSDT', icon: 'aave', thumb: 'aave.png'},
  {name: 'Loopring', symbol: 'LRCUSD', live: 'LRCUSDT', icon: 'lrc', thumb: 'lrc.png'},
  {name: 'IOTA', symbol: 'IOTAUSD', live: 'IOTAUSDT', icon: 'miota', thumb: 'iota.png'},
  {name: 'Neo', symbol: 'NEOUSD', live: 'NEOUSDT', icon: 'neo', thumb: 'neo.png'},
  {name: 'Maker', symbol: 'MKRUSD', live: 'MKRUSDT', icon: 'mkr', thumb: 'mkr.png'},
  {name: 'Enjin', symbol: 'ENJUSD', live: 'ENJUSDT', icon: 'enj', thumb: 'enj.png'},
  {name: 'Dash', symbol: 'DASHUSD', live: 'DASHUSDT', icon: 'dash', thumb: 'dash.png'},
  {name: 'Compound', symbol: 'COMPUSD', live: 'COMPUSDT', icon: 'comp', thumb: 'comp.png'},
  {name: 'CRV', symbol: 'CRVUSD', live: 'CRVUSDT', icon: 'crv', thumb: 'crv.png'},
  {name: 'BAT', symbol: 'BATUSD', live: 'BATUSDT', icon: 'bat', thumb: 'bat.png'},
  {name: 'SushiSwap', symbol: 'SUSHIUSD', live: 'SUSHIUSDT', icon: 'sushi', thumb: 'sushi.png'},
  {name: 'Zilliqa', symbol: 'ZILUSD', live: 'ZILUSDT', icon: 'zil', thumb: 'zil.png'},
  {name: 'yearn.finance', symbol: 'YFIUSD', live: 'YFIUSDT', icon: 'yfi', thumb: 'yfi.png'},
  {name: '1inch', symbol: '1INCHUSD', live: '1INCHUSDT', icon: 'oneinch', thumb: 'oneinch.png'},
];
export let defi = [
  {name: 'Curve', symbol: 'CRV'},
  {name: 'Terra', symbol: 'LUNA'},
  {name: 'Chainlink', symbol: 'LINK'},
  {name: 'Uniswap', symbol: 'UNI'},
  {name: 'Dai', symbol: 'DAI'},
  {name: 'cETH', symbol: 'CETH', icon: 'ceth'},
  {name: 'Lido Staked Ether', symbol: 'STETH', icon: 'lido'},
  {name: 'The Graph', symbol: 'GRT'},
  {name: 'cDAI', symbol: 'CDAI', icon: 'cdai'},
  {name: 'PancakeSwap', symbol: 'CAKE'},
  {name: 'Aave', symbol: 'AAVE'},
];
// NFTs
// Axie Infinity AXS
// Theta Network THETA
// Decentraland MANA
// Flow FLOW
// Chiliz CHZ
// Enjin Coin ENJ
// The Sandbox SAND
// ECOMI OMI
// WAX WAXP
// Audius AUDIO
export let currencies = [
  {name: 'EUR/USD', symbol: 'EURUSD', icon: 'eurusd', type: 'currency'},
  {name: 'USD/JPY', symbol: 'USDJPY', icon: 'usdjpy', type: 'currency'},
  {name: 'USD/KRW', symbol: 'USDKRW', icon: 'usdkrw', type: 'currency'},
  {name: 'USD/TRY', symbol: 'USDTRY', icon: 'usdtry', type: 'currency'},
  {name: 'GBP/USD', symbol: 'GBPUSD', icon: 'gbpusd', type: 'currency'},
  {name: 'USD/BRL', symbol: 'USDBRL', icon: 'usdbrl', type: 'currency'},
  {name: 'USD/ILS', symbol: 'USDILS', icon: 'usdils', type: 'currency'},
  {name: 'USD/RUB', symbol: 'USDRUB', icon: 'usdrub', type: 'currency'},
  {name: 'Dollar Index', symbol: 'DXY', icon: 'usa', type: 'currency'},
  {name: 'XAU/USD', symbol: 'XAUUSD', icon: 'gold', type: 'commodity'},
  {name: 'XAG/USD', symbol: 'XAGUSD', icon: 'silver', type: 'commodity'},
  {name: 'WTI/USD', symbol: 'WTIUSD', icon: 'crude-oil', type: 'commodity'},
  {name: 'XBR/USD', symbol: 'XBRUSD', icon: 'brent-oil', type: 'commodity'},
];
export let stocks = [
  {name: 'Apple', symbol: 'AAPL', icon: 'apple', thumb: 'apple.jpg'},
  {name: 'Pfizer', symbol: 'PFE', icon: 'pfizer', thumb: 'pfizer.jpg'},
  {name: 'Amazon', symbol: 'AMZN', icon: 'amazon', thumb: 'amazon.jpg'},
  {name: 'Facebook', symbol: 'FB', icon: 'facebook', thumb: 'facebook.jpg'},
  {name: 'Microsoft', symbol: 'MSFT', icon: 'microsoft', thumb: 'microsoft.png'},
  {name: 'Moderna', symbol: 'MRNA', icon: 'moderna', thumb: 'moderna.jpg'},
  {name: 'NIO', symbol: 'NIO', icon: 'nio', thumb: 'nio.jpg'},
  {name: 'Tesla', symbol: 'TSLA', icon: 'tesla', thumb: 'tesla.jpg'},
  {name: 'Nvidia', symbol: 'NVDA', icon: 'nvidia', thumb: 'nvidia.png'},
  {name: 'Xpeng', symbol: 'XPEV', icon: 'xpeng', thumb: 'xpeng.png'},
  {name: 'Palantir', symbol: 'PLTR', icon: 'palantir', thumb: 'palantir.png'},
  {name: 'Boeing', symbol: 'BA', icon: 'boeing', thumb: 'boeing.jpg'},
  {name: 'Santander', symbol: 'SAN', icon: 'santander', thumb: 'santander.png'},
  {name: 'Alibaba', symbol: 'BABA', icon: 'alibaba', thumb: 'alibaba.png'},
  {name: 'Gamestop', symbol: 'GME', icon: 'gme', thumb: 'gamestop.png'},
  {name: 'AMC', symbol: 'AMC', icon: 'amc', thumb: 'amc.jpg'},
  {name: 'BlackBerry', symbol: 'BB', icon: 'blackberry', thumb: 'blackberry.png'}
];
export let indices = [
  {name: 'NASDAQ', symbol: 'IXIC', icon: 'usa', type: 'indice'},
  {name: 'NASDAQ RTD*', symbol: 'IXIC', icon: 'usa', type: 'indice', cfd: true, country: "US"},
  {name: 'DOW JONES', symbol: 'DJI', icon: 'usa', type: 'indice'},
  {name: 'DOW JONES RTD*', symbol: 'DJI', icon: 'usa', type: 'indice', cfd: true, country: "US"},
  {name: 'S&P 500', symbol: 'GSPC', icon: 'usa', type: 'indice'},
  {name: 'S&P 500 RTD*', symbol: 'GSPC', icon: 'usa', type: 'indice', cfd: true, country: "US"},
  {name: 'FTSE', symbol: 'FTSE', icon: 'uk', type: 'indice'},
  {name: 'FTSE RTD*', symbol: 'FTSE', icon: 'uk', type: 'indice', cfd: true, country: "GB"},
  {name: 'NIKKEI', symbol: 'N225', icon: 'jp', type: 'indice'},
  {name: 'NIKKEI Futures RTD*', symbol: 'N225', icon: 'jp', type: 'indice', cfd: true, country: "JP"},
  {name: 'HANG SENG', symbol: 'HSI', icon: 'hk', type: 'indice'},
  {name: 'HANG SENG RTD*', symbol: 'HSI', icon: 'hk', type: 'indice', cfd: true, country: "HK"},
  {name: 'SHANGHAI', symbol: '000001', icon: 'cn', type: 'indice'},
  {name: 'SHANGHAI RTD*', symbol: '000001', icon: 'cn', type: 'indice', cfd: true, country: "CN"},
  {name: 'KOSPI', symbol: 'KS11', icon: 'ko', type: 'indice'},
  {name: 'KOSPI RTD*', symbol: 'KS11', icon: 'ko', type: 'indice', cfd: true, country: "KO"},
  {name: 'DAX', symbol: 'GDAXI', icon: 'germany', type: 'indice'},
  {name: 'DAX RTD*', symbol: 'GDAXI', icon: 'germany', type: 'indice', cfd: true, country: "DE"},
  {name: 'IBEX 35', symbol: 'IBEX', icon: 'spain', type: 'indice'},
  {name: 'IBEX 35 RTD*', symbol: 'IBEX', icon: 'spain', type: 'indice', cfd: true, country: "ES"},
  {name: 'BIST 100', symbol: 'XU100', icon: 'turkey', type: 'indice'},
  {name: 'BIST 100 RTD*', symbol: 'XU100', icon: 'turkey', type: 'indice', cfd: true, country: "TR"},
  {name: 'Dollar Index', symbol: 'DXY', icon: 'usa', type: 'currency'},
  {name: 'US 1M Bond', symbol: 'DGS1MO', icon: 'usa'},
  {name: 'US 3M Bond', symbol: 'DGS3MO', icon: 'usa'},
  {name: 'US 6M Bond', symbol: 'DGS6MO', icon: 'usa'},
  {name: 'US 1 Year Bond', symbol: 'DGS1', icon: 'usa'},
  {name: 'US 2 Year Bond', symbol: 'DGS2', icon: 'usa'},
  {name: 'US 5 Year Bond', symbol: 'DGS5', icon: 'usa'},
  {name: 'US 7 Year Bond', symbol: 'DGS7', icon: 'usa'},
  {name: 'US 10 Year Bond', symbol: 'DGS10', icon: 'usa'},
  {name: 'US 20 Year Bond', symbol: 'DGS20', icon: 'usa'},
  {name: 'US 30 Year Bond', symbol: 'DGS30', icon: 'usa'},
];
export let bonds = [
  {name: 'US 1M Bond', symbol: 'DGS1MO', icon: 'usa'},
  {name: 'US 3M Bond', symbol: 'DGS3MO', icon: 'usa'},
  {name: 'US 6M Bond', symbol: 'DGS6MO', icon: 'usa'},
  {name: 'US 1 Year Bond', symbol: 'DGS1', icon: 'usa'},
  {name: 'US 2 Year Bond', symbol: 'DGS2', icon: 'usa', type: 'homeBond'},
  {name: 'US 5 Year Bond', symbol: 'DGS5', icon: 'usa', type: 'homeBond'},
  {name: 'US 7 Year Bond', symbol: 'DGS7', icon: 'usa'},
  {name: 'US 10 Year Bond', symbol: 'DGS10', icon: 'usa', type: 'homeBond'},
  {name: 'US 20 Year Bond', symbol: 'DGS20', icon: 'usa', type: 'homeBond'},
  {name: 'US 30 Year Bond', symbol: 'DGS30', icon: 'usa', type: 'homeBond'},
];

export let rising = []
// export let commodities = [
//   // {name: 'Carbon Emissions', symbol: 'CARBON', icon: 'carbon'},
//   {name: 'Gold', symbol: 'XAUUSD', icon: 'gold'},
//   {name: 'Silver', symbol: 'XAGUSD', icon: 'silver'},
//   // {name: 'Bitcoin Futures', symbol: 'BTCUSD', icon: 'btc'},
//   // {name: 'Natural Gas', symbol: 'NGAS', icon: 'natgas'},
//   {name: 'Crude Oil', symbol: 'WTIUSD', icon: 'crude-oil'},
//   {name: 'Brent Oil', symbol: 'XBRUSD', icon: 'brent-oil'},
//   // {name: 'US Coffee C', symbol: 'USCOFFEEC', icon: 'coffee'},
// ];

export let commodities = [
  {name: 'EU Carbon Emissions', symbol: 'EECXM:IND', icon: 'carbon'},
  {name: 'Gold', symbol: 'XAUUSD:CUR', icon: 'gold'},
  {name: 'Silver', symbol: 'XAGUSD:CUR', icon: 'silver'},
  {name: 'Natural Gas', symbol: 'NG1:COM', icon: 'natgas'},
  {name: 'Crude Oil', symbol: 'CL1:COM', icon: 'crude-oil'},
  {name: 'Brent Oil', symbol: 'CO1:COM', icon: 'brent-oil'},
  {name: 'Coffee', symbol: 'KC1:COM', icon: 'coffee'},
  {name: 'Platinum', symbol: 'XPTUSD:CUR', icon: 'platinum'},
  {name: 'Cobalt', symbol: 'LCO1:COM', icon: 'cobalt'},
  {name: 'Solar Energy Index', symbol: 'SOLARNTR:IND', icon: 'solar'},
  {name: 'Wind Energy Index', symbol: 'GWETR:IND', icon: 'wind'},
  {name: 'CRB Index', symbol: 'CRYTR:IND', icon: 'crb'},
  {name: 'LME Index', symbol: 'LME:IND', icon: 'lme'},
];