export let cryptocurrency = [
  {name: 'Bitcoin', symbol: 'BTCUSD', icon: 'btc', thumb: 'bitcoin.jpg'},
  {name: 'Ethereum', symbol: 'ETHUSD', icon: 'eth', thumb: 'ethereum.png'},
  {name: 'IOTA', symbol: 'IOTAUSD', icon: 'iota', thumb: 'iota.png'},
  {name: 'Cardano', symbol: 'ADAUSD', icon: 'cardano', thumb: 'cardano.jpg'},
  {name: 'XRP', symbol: 'XRPUSD', icon: 'xrp', thumb: 'xrp.png'},
  {name: 'Polkadot', symbol: 'DOTUSD', icon: 'polkadot', thumb: 'polkadot.png'},
  {name: 'Dogecoin', symbol: 'DOGEUSD', icon: 'doge', thumb: 'doge.jpg'}
];
export let currencies = [
  {name: 'EUR/USD', symbol: 'EURUSD', icon: 'eurusd', type: 'currency'},
  {name: 'USD/JPY', symbol: 'USDJPY', icon: 'usdjpy', type: 'currency'},
  {name: 'USD/KRW', symbol: 'USDKRW', icon: 'usdkrw', type: 'currency'},
  {name: 'USD/TRY', symbol: 'USDTRY', icon: 'usdtry', type: 'currency'},
  {name: 'GBP/USD', symbol: 'GBPUSD', icon: 'gbpusd', type: 'currency'},
  {name: 'USD/BRL', symbol: 'USDBRL', icon: 'usdbrl', type: 'currency'},
  {name: 'USD/ILS', symbol: 'USDILS', icon: 'usdils', type: 'currency'},
  {name: 'USD/RUB', symbol: 'USDRUB', icon: 'usdrub', type: 'currency'},
  {name: 'Dollar Index', symbol: 'DXY', icon: 'usa', type: 'currency'},
  {name: 'XAU/USD', symbol: 'XAUUSD', icon: 'gold', type: 'commodity'},
  {name: 'XAG/USD', symbol: 'XAGUSD', icon: 'silver', type: 'commodity'},
  {name: 'WTI/USD', symbol: 'WTIUSD', icon: 'crude-oil', type: 'commodity'},
  {name: 'XBR/USD', symbol: 'XBRUSD', icon: 'brent-oil', type: 'commodity'},
];
export let stocks = [
  {name: 'Apple', symbol: 'AAPL', icon: 'apple', thumb: 'apple.jpg'},
  {name: 'Pfizer', symbol: 'PFE', icon: 'pfizer', thumb: 'pfizer.jpg'},
  {name: 'Amazon', symbol: 'AMZN', icon: 'amazon', thumb: 'amazon.jpg'},
  {name: 'Facebook', symbol: 'FB', icon: 'facebook', thumb: 'facebook.jpg'},
  {name: 'Microsoft', symbol: 'MSFT', icon: 'microsoft', thumb: 'microsoft.png'},
  {name: 'Moderna', symbol: 'MRNA', icon: 'moderna', thumb: 'moderna.jpg'},
  {name: 'NIO', symbol: 'NIO', icon: 'nio', thumb: 'nio.jpg'},
  {name: 'Tesla', symbol: 'TSLA', icon: 'tesla', thumb: 'tesla.jpg'},
  {name: 'Nvidia', symbol: 'NVDA', icon: 'nvidia', thumb: 'nvidia.png'},
  {name: 'Xpeng', symbol: 'XPEV', icon: 'xpeng', thumb: 'xpeng.png'},
  {name: 'Palantir', symbol: 'PLTR', icon: 'palantir', thumb: 'palantir.png'},
  {name: 'Boeing', symbol: 'BA', icon: 'boeing', thumb: 'boeing.jpg'},
  {name: 'Santander', symbol: 'SAN', icon: 'santander', thumb: 'santander.png'},
  {name: 'Alibaba', symbol: 'BABA', icon: 'alibaba', thumb: 'alibaba.png'},
  {name: 'Gamestop', symbol: 'GME', icon: 'gme', thumb: 'gamestop.png'},
  {name: 'AMC', symbol: 'AMC', icon: 'amc', thumb: 'amc.jpg'},
  {name: 'BlackBerry', symbol: 'BB', icon: 'blackberry', thumb: 'blackberry.png'}
];
export let indices = [
  {name: 'NASDAQ', symbol: 'IXIC', icon: 'usa', type: 'indice'},
  {name: 'NASDAQ CFD', symbol: 'IXIC', icon: 'usa', type: 'indice', cfd: true},
  {name: 'DOW JONES', symbol: 'DJI', icon: 'usa', type: 'indice'},
  {name: 'DOW JONES CFD', symbol: 'DJI', icon: 'usa', type: 'indice', cfd: true},
  {name: 'S&P 500', symbol: 'GSPC', icon: 'usa', type: 'indice'},
  {name: 'S&P 500 CFD', symbol: 'GSPC', icon: 'usa', type: 'indice', cfd: true},
  {name: 'FTSE', symbol: 'FTSE', icon: 'uk', type: 'indice'},
  {name: 'FTSE CFD', symbol: 'FTSE', icon: 'uk', type: 'indice', cfd: true},
  {name: 'NIKKEI', symbol: 'N225', icon: 'jp', type: 'indice'},
  {name: 'NIKKEI CFD', symbol: 'N225', icon: 'jp', type: 'indice', cfd: true},
  {name: 'HANG SENG', symbol: 'HSI', icon: 'hk', type: 'indice'},
  {name: 'HANG SENG CFD', symbol: 'HSI', icon: 'hk', type: 'indice', cfd: true},
  {name: 'SHANGHAI', symbol: 'SSEC', icon: 'cn', type: 'indice'},
  {name: 'SHANGHAI CFD', symbol: 'SSEC', icon: 'cn', type: 'indice', cfd: true},
  {name: 'KOSPI', symbol: 'KS11', icon: 'ko', type: 'indice'},
  {name: 'KOSPI CFD', symbol: 'KS11', icon: 'ko', type: 'indice', cfd: true},
  {name: 'DAX', symbol: 'GDAXI', icon: 'germany', type: 'indice'},
  {name: 'DAX CFD', symbol: 'GDAXI', icon: 'germany', type: 'indice', cfd: true},
  {name: 'IBEX 35', symbol: 'IBEX', icon: 'spain', type: 'indice'},
  {name: 'IBEX 35 CFD', symbol: 'IBEX', icon: 'spain', type: 'indice', cfd: true},
  {name: 'BIST 100', symbol: 'XU100', icon: 'turkey', type: 'indice'},
  {name: 'BIST 100 CFD', symbol: 'XU100', icon: 'turkey', type: 'indice', cfd: true},
  {name: 'Dollar Index', symbol: 'DXY', icon: 'usa', type: 'currency'},
  {name: 'US 1M Bond', symbol: 'DGS1MO', icon: 'usa'},
  {name: 'US 3M Bond', symbol: 'DGS3MO', icon: 'usa'},
  {name: 'US 6M Bond', symbol: 'DGS6MO', icon: 'usa'},
  {name: 'US 1 Year Bond', symbol: 'DGS1', icon: 'usa'},
  {name: 'US 2 Year Bond', symbol: 'DGS2', icon: 'usa'},
  {name: 'US 5 Year Bond', symbol: 'DGS5', icon: 'usa'},
  {name: 'US 7 Year Bond', symbol: 'DGS7', icon: 'usa'},
  {name: 'US 10 Year Bond', symbol: 'DGS10', icon: 'usa'},
  {name: 'US 20 Year Bond', symbol: 'DGS20', icon: 'usa'},
  {name: 'US 30 Year Bond', symbol: 'DGS30', icon: 'usa'},
];
export let bonds = [
  {name: 'US 1M Bond', symbol: 'DGS1MO', icon: 'usa'},
  {name: 'US 3M Bond', symbol: 'DGS3MO', icon: 'usa'},
  {name: 'US 6M Bond', symbol: 'DGS6MO', icon: 'usa'},
  {name: 'US 1 Year Bond', symbol: 'DGS1', icon: 'usa'},
  {name: 'US 2 Year Bond', symbol: 'DGS2', icon: 'usa', type: 'homeBond'},
  {name: 'US 5 Year Bond', symbol: 'DGS5', icon: 'usa', type: 'homeBond'},
  {name: 'US 7 Year Bond', symbol: 'DGS7', icon: 'usa'},
  {name: 'US 10 Year Bond', symbol: 'DGS10', icon: 'usa', type: 'homeBond'},
  {name: 'US 20 Year Bond', symbol: 'DGS20', icon: 'usa', type: 'homeBond'},
  {name: 'US 30 Year Bond', symbol: 'DGS30', icon: 'usa', type: 'homeBond'},
];
export let rising = [
  // {name: 'Tesla', symbol: 'TSLA', icon: 'tesla'},
  // {name: 'Gamestop', symbol: 'GME', icon: 'gme'},
  // {name: 'AMC', symbol: 'AMC', icon: 'amc'},
  // {name: 'BlackBerry', symbol: 'BB', icon: 'blackberry'},
  // {name: 'Dogecoin', symbol: 'DOGEUSD', icon: 'doge'},
];
export let commodities = [
  // {name: 'Carbon Emissions', symbol: 'CARBON', icon: 'carbon'},
  {name: 'Gold', symbol: 'XAUUSD', icon: 'gold'},
  {name: 'Silver', symbol: 'XAGUSD', icon: 'silver'},
  // {name: 'Bitcoin Futures', symbol: 'BTCUSD', icon: 'btc'},
  // {name: 'Natural Gas', symbol: 'NGAS', icon: 'natgas'},
  {name: 'Crude Oil', symbol: 'WTIUSD', icon: 'crude-oil'},
  {name: 'Brent Oil', symbol: 'XBRUSD', icon: 'brent-oil'},
  // {name: 'US Coffee C', symbol: 'USCOFFEEC', icon: 'coffee'},
];