<template>
  <div class="container content buffer pb-5">
    <div class="row d-flex justify-content-center">
      <div class="col-11 white-well">
        <h2 class="mb-4 pt-3">Terms &amp; Conditions</h2>
        <p>The following describes the terms and conditions (the “ <span class="bold"> Terms and Conditions </span> ”) upon which Urala Communications Limited (the “ <span class="bold"> Company </span> ” or “ <span class="bold"> Urala Communications </span> ” or “ <span class="bold"> We </span> ”) offers access to the Internet site found at www.the-markets.com alongside its related country specific sites and any related sub-domains and/or mobile applications thereof (respectively, the “ <span class="bold"> Site </span> ” or “ <span class="bold"> App </span> ”, and together the “ <span class="bold"> Services </span> ”) to you the customer, irrespective of whether or not you are an Account (as defined below) holder (“ <span class="bold"> you </span> ” or “ <span class="bold"> You </span> ”)“”.</p>
        <p>PLEASE READ THE PRIVACY POLICY, COOKIE POLICY, RISK WARNING AND ALL OF THE FOLLOWING TERMS AND CONDITIONS INCLUDING THE SPECIAL CONDITIONS BEFORE USING OUR SERVICES. BY CONTINUING TO ACCESS OR USE OUR SERVICES, YOU SIGNIFY YOUR ACCEPTANCE OF THESE TERMS AND CONDITIONS. We reserve the right to amend, remove, or add to these Terms and Conditions at any time. Please check the “Last modified” heading at the top of this document to see when the Terms and Conditions were last updated. Any changes to the Terms and Conditions will become effective when we post the revised Terms and Conditions. Your use of the Services, or your provision of personal information following any changes means that you accept the updated Terms and Conditions.</p>
        <p>If, at any time, you do not wish to accept the Terms and Conditions, you may not use our Services. Any terms and conditions proposed by you which are in addition to, or which conflict with these Terms and Conditions are expressly rejected by the Company and will have no force or effect.</p>
        <p>You understand and agree that Urala Communications may discontinue or change the Services at any time, without notice. You also understand and agree that Urala Communications may discontinue or restrict your use of the Services for any reason without notice.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Your Account</h3>
        <p>As part of the process necessary to set up an account on the Services (an “ <span class="bold"> Account </span> ”) and obtain access to certain parts of the Services, you will be required to either provide your full name, email address, password, and phone number (the “ <span class="bold"> Registration Credentials </span> ”) or register via one of the Third Party Accounts (as defined below). You must ensure that your Registration Credentials are accurate, truthful and updated. We reserve the right to block the creation of your Account based on our inability to confirm the authenticity of your Registration Credentials.</p>
        <p>As an alternative to registering directly with the Site or App by providing your Registration Credentials, we give you the option to register and login to your Account via one of your account(s) with social media sites such as Facebook, Twitter or Google+ (the “ <span class="bold"> Third Party Account(s) </span> ”). Please see our&nbsp; <a href="/privacy-policy"> Privacy Policy </a> &nbsp;for more information about logging in to your Account via a Third Party Account.</p>
        <p>Unless you log into your Account via a Third Party Account, please note that your email address and password which you provide as part of the Registration Credentials will be used to login in to your Account. You will be solely responsible for maintaining the confidentiality of your email address and password and must immediately notify us of any unauthorized use of your Account. You are solely responsible for all activity and usage on your Account, including, but not limited to, use of the Account by any third party authorized by you to use your email address and password.</p>
        <p>We permit you to maintain only one Account to access the Services at any time and you hereby represent that you currently have no other Account(s).</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Ad-free Services</h3>
        <p>Our basic Services are free, but we may offer You paid upgrades for advanced features such as “ad-free” version of the Services (“ <span class="bold"> Ad-free Services </span> ”).</p>
        <p>You may purchase Ad-free Services, which include, subject to a specific policy/ies of an various app stores (such as Google Play or Apple App Store(, and applicable law, a removal of all the ads on Your Account in all related online platforms, including from our Site and our App, which are available for use in such app stores. These Ad-free Services will be available to You only when You are signed-in to our Services.</p>
        <p><span class="bold"> Payment. </span> &nbsp;In order to purchase Ad-free Services, You will be required to make the payments specified in the Ad-free Services dedicated offering page, using a payment method made available to You. You represent that you are at least the minimum age required to enter into a legal agreement. In order for You to make such purchase, we may direct you to our trusted payment service providers' websites. You may be required to share with payment service providers Your personal information (such as your name, address, identity number), financial information (e.g. your credit card number, bank account, etc.) and any other information which is required by the payment service providers in order to complete the purchase of the Ad-free Services. We may change the rates of the Ad-free Services from time to time and in our sole discretion.</p>
        <p><span class="bold"> Renewals. </span> &nbsp;Unless You cancel your Ad-free Services subscription at least 48 hours before the end of the current subscription period, the Ad-free Services are renewed automatically every subscription period to which You have&nbsp; subscribed, and the charges for such renewed period are made automatically through the payment service provider you have used initially to purchase the Ad-free Services.</p>
        <p><span class="bold"> No Refunds. </span> &nbsp;Notwithstanding anything to the contrary (but subject to any applicable law), all charges for the Ad-free Services are non-refundable. However, if you believe that you have been charged in error or if you believe you should be refunded for any other reason, you should contact us within 60 days of such charge. We reserve the right to refuse such a refund request for any reason, including if we reasonably believe (i) that you are trying to unfairly exploit this refund policy, for example, by making repetitive refund requests in respect of the same feature; (ii) if you are in breach of the Terms; or (iii) if we reasonably suspect that you are using our Services fraudulently.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Subscription-Based Services</h3>
        <p>We offer services, products, and subscriptions for a subscription fee (respectively, “ <span class="bold"> Subscription </span> <span class="bold"> Based </span> <span class="bold"> Services </span> ” and “ <span class="bold"> Subscription Fee </span> ”).</p>
        <p>These Subscription Based Services are governed by any additional terms you agree to when you register for the Subscription Based Services (including any third party’s terms of service, privacy policy and other relevant policies providing any such Subscription Based Service, which you should read thoroughly before agreeing to them) and these Terms. &nbsp;If you register for Subscription Based Services, you agree to pay the applicable Subscription Fees set forth on the Site and/or App and must designate a payment method and provide us with accurate billing and payment information, and you have the continuing obligation to keep it up to date. If the Subscription Based Services includes a third-party product or service, you understand and agree that your purchase and use of the Service is also subject to the third party’s terms of service and privacy policy, which you should read thoroughly before agreeing to them. Urala Communications assume no liability or responsibility on such products or services when it is provided by a third party.&nbsp;</p>
        <p><span class="bold"> Payment </span> . You represent that you are at least the minimum age required to enter into a legal agreement. You agree to pay us for any Subscription Based Services you purchase from us (or a third party), as well as all other charges incurred under your account, including applicable taxes and fees. You are responsible for all charges incurred under your account, including purchases made by you or anyone you allow to use your account or any sub-or linked accounts (including any person with implied, actual, or apparent authority) or anyone who gains access to your account as a result of your failure to safeguard your authentication credentials. You authorize and direct us to charge your designated payment method for these charges or, if it fails, to charge any other payment method you have on file with us, even if we received it in association with other Subscription Based Services. You are responsible for all charges even if your payment method fails or is denied. You authorize and direct us to retain all information about any payment method(s) associated with your account. We may import payment information you entered during a prior purchase and provide you the option to use that payment information during purchase of a new product. You permit us to obtain and use updated information from the issuer of your payment method in accordance with the policies and procedures of any applicable card brands. We may in some instances continue charging a payment method past its expiration date at our discretion and subject to the payment processors' or issuing bank's approval. Surcharges may apply if you use certain payment methods, such as payment from your checking or savings account. We may charge for Subscription Based Services in advance and on a daily, monthly, yearly, lump sum, or other basis in accordance with the stated terms, as long as your subscription remains active, even if you have not downloaded or used such Service or accessed your online account. We may (and you authorize us to) take steps to verify the validity of the credit card information you provide to us. You authorize us to do so for verification and anti-fraud purposes.</p>
        <p><span class="bold"> Renewal </span> . We use auto-renewal for many of our Subscription Based Services. At the expiration of each subscription term for such Subscription Based Services, we will automatically renew your subscription and charge the credit card or other payment method you have provided to us, unless you cancel your subscription at least 48 hours before the end of the current subscription period. Unless otherwise stated herein, your subscription will be automatically renewed at the then-current price, excluding promotional and discount pricing. We may, in our sole discretion, post charges to your payment method individually or aggregate charges for some or all of your Subscription Based Services with us.</p>
        <p><span class="bold"> Fraud Protection </span> . We may take steps to verify the validity of the credit card information you provide to us, including debiting amounts less than $1.00 from your credit card and then immediately crediting it back. You authorize us to do so for verification and anti-fraud purposes.</p>
        <p><span class="bold"> Free </span> <span class="bold"> Trials </span> . We may offer you free trials, so that you may try a Subscription Based Services subscription without charge or obligation (“Free Trial”). Unless otherwise stated and unless you cancel your subscription prior to the expiration of the Free Trial, periodic subscription fees will be charged at the then-applicable rate upon expiration of the Free Trial period and will continue to be charged until the subscription is canceled or expired. If you are not satisfied with a particular Subscription Based Services, you must cancel the subscription before the Free Trial ends to avoid charges. We reserve the right to limit you to one free trial or promotion of a Subscription Based Services and to prohibit the combining of free trials or other promotional offers.</p>
        <p>Termination. We, in our sole discretion, may change, discontinue or terminate any or all aspects of a Subscription Based Services without notice, including access to support services, content and other products or services ancillary to the Subscription Based Services, subject to providing an appropriate refund for any portions of a specified but no longer available term.</p>
        <p><span class="bold"> No Refunds </span> . Notwithstanding anything to the contrary set forth herein (but subject to any applicable law), all charges for a Subscription Based Services are nonrefundable unless provided otherwise in the terms you agree to when you register for a Subscription Based Services. However, if you believe that you have been charged in error or if you believe you should be refunded for any other reason, you should contact us within 60 days of such charge. We reserve the right to refuse such a refund request for any reason, including if we reasonably believe (i) that you are trying to unfairly exploit this refund policy, for example, by making repetitive refund requests in respect of the same feature; (ii) if you are in breach of the Terms; or (iii) if we reasonably suspect that you are using the Subscription Based Services fraudulently.</p>
        <p><span class="bold"> Change in Fees and Billing Method </span> . We may change our fees and billing methods at any time. We will provide you with notice of any price increase at least thirty (30) days in advance. Subject to applicable law, (i) if you disagree with any proposed change, your sole remedy is to cancel your Subscription Based Services before the price change takes effect and (ii) your continued use of or subscription to the Subscription Based Service after the price change takes effect constitutes your agreement to pay the new price for the Subscription Based Service.</p>
        <p><span class="bold"> Delinquency </span> . After 30 days from the date of any unpaid charges, your Subscription Based Services will be deemed delinquent and we may terminate or suspend your account and Subscription Based Service for nonpayment. You are liable for any fees, including attorney and collection fees, incurred by us in our efforts to collect any remaining balances from you.</p>
        <p><span class="bold"> Notice Period </span> . You must notify us about any billing problems or discrepancies within 90 days after they first appear on your billing method statement. If you do not bring them to our attention within 90 days, you agree that you waive your right to dispute such problems or discrepancies.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Disclaimer</h3>
        <p>Due to the number of sources from which the content presented on our Services is obtained, and the inherent hazards of electronic distribution, there may be delays, omissions or inaccuracies in such content and the Services.</p>
        <p>THE SERVICES, AND ANY MATERIAL AND/OR CONTENT APPEARING THEREON (“ <span class="bold"> CONTENT </span> ”) ARE PROVIDED “AS IS”, WITHOUT ANY WARRANTIES. Urala Communications, ITS EMPLOYEES, OFFICERS, DIRECTORS, AFFILIATES, AGENTS AND LICENSORS CANNOT AND DO NOT WARRANT THE ACCURACY, COMPLETENESS, CURRENTNESS, TIMELINESS, NONINFRINGEMENT, TITLE, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OF THE CONTENT AVAILABLE THROUGH THE SERVICES, OR THE SERVICES THEMSELVES, AND Urala Communications HEREBY DISCLAIMS ANY SUCH EXPRESS OR IMPLIED WARRANTIES.</p>
        <p>IN NO EVENT SHALL Urala Communications, ITS EMPLOYEES, OFFICERS, DIRECTORS, AFFILIATES, AGENTS OR LICENSORS BE LIABLE TO YOU OR TO ANY THIRD PARTY OR TO ANYONE ELSE FOR ANY KIND OF FINANCIAL LOSS, LOST PROFITS, ANY SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGE OR ANY OTHER SIMILAR DAMAGE OR ANY OTHER LOSS OR INJURY, RESULTING DIRECTLY OR INDIRECTLY FROM USE OF THE SERVICES, CAUSED IN WHOLE OR PART BY ITS NEGLIGENCE OR CONTINGENCIES BEYOND ITS CONTROL IN PROCURING, COMPILING, INTERPRETING, REPORTING OR DELIVERING THE SERVICESAND ANY CONTENT ON THEREON.</p>
        <p>IN NO EVENT SHALL Urala Communications, ITS EMPLOYEES, OFFICERS, DIRECTORS, AFFILIATES, AGENTS OR LICENSORS BE LIABLE TO YOU OR ANY THIRD PARTY OR ANY ONE ELSE FOR ANY DECISION MADE OR ACTION TAKEN BY YOU IN RELIANCE ON SUCH CONTENT ON THE SERVICESOR THE SERVICES THEMSELVES.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Legal Restrictions</h3>
        <p>Without limiting the foregoing, you understand that laws regarding financial contracts vary throughout the world, and it is your sole obligation to ensure that you fully comply with any law, regulation or directive, applicable to your country of residence with regards to the use of the Services. The ability to access to our Services does not necessarily mean that our Services, and/or your activities via the Services, are legal under the laws, regulations or directives applicable to your country of residence.</p>
        <p>The Services does not constitute, and may not be used for the purposes of, an offer or solicitation to anyone in any jurisdiction in which such an offer or solicitation is not authorized, or to any person to whom it is unlawful to make such an offer or solicitation. Access to the Services, and the offering of financial contracts via our Services, may be restricted in certain jurisdictions, and, accordingly, users accessing our Services are required to inform themselves of, and to observe, such restrictions.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Limited License</h3>
        <p>Urala Communications grants you a non-exclusive, non-transferable and limited personal license to access and use the Services (the “ <span class="bold"> License </span> ”). This License is conditional on your full and continuing compliance with these Terms and Conditions. You agree not to “deep-link” to the Services, resell or permit access to the Services to others, and not to copy any materials appearing on the Services for resale or for any other purpose to others without the prior written consent of Urala Communications. You shall be responsible and bound by any unauthorized use of the Services, made in breach of this section. You agree not to use any electronic communication feature of Services on the Services for any purpose that is unlawful, tortious, abusive, and intrusive on another's privacy, harassing, libelous, defamatory, embarrassing, obscene, threatening or hateful. The License granted under these Terms and Conditions will terminate if Urala Communications believes that any information provided by you, including (but not limited to) your Registration Credentials, is no longer current or accurate, or if you fail to otherwise comply with any term or condition of these Terms and Conditions and all rules and guidelines for each of the Services. Upon such violation, you agree to cease accessing Services. You agree that Urala Communications, at its sole discretion and with or without notice, may terminate your access to any or all Services, and remove and discard any information or content within the Services.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Links to Third Party Sites and Use of Third Party Software</h3>
        <p>The Services contain hyperlinks to websites operated by persons other than Urala Communications. Such hyperlinks are provided for your reference and convenience only. You agree not to hold Urala Communications responsible for the content or operation of such websites. A hyperlink from our Services to another website does not imply that Urala Communications endorses the content on that website or the operator or operations of that website. You are solely responsible for determining the extent to which you may use any content or such web-site.</p>
        <p>Furthermore, certain parts of the Services contain third-party software, including but not limited to “open source” software. Use of third-party software may be governed by separate copyright notices and license provisions, which shall be made available to you, as applicable, either by Company or by such third-party software provider. You shall not use, and shall indemnify and hold Company harmless for any such use by or on behalf of You, in a manner which infringes the rights of any third-party or which is in contravention to these Terms and Conditions and/or any specific license terms.</p>
        <p>For example, some payment options on our Services are provided by third party payment processors who process your payments on our behalf (such as Apple or Google through “ <span class="bold"> In-App Purchases </span> ”, as described below). If you wish to make a purchase on the Services, you may also be asked to supply certain information, including credit card, debit card, Apple ID or Google ID or other payment mechanism information directly to such payment processor.</p>
        <p>You agree that all information you provide in connection with such purchase will be accurate, complete and current. You agree to pay all charges incurred by use of your credit card, debit card, Apple Pay, Google Pay, or other payment mechanism at the prices in effect when such charges are incurred. You also will pay any applicable taxes relating to any purchases you make.</p>
        <p>You further acknowledge that your use of any third parties' site and or software is subject to the applicable third party's terms and conditions, and you further agree not to hold Urala Communications liable for any loss or damage of any sort incurred as a result of any such use by You.</p>
        <p>THE LIABILITY OF Urala Communications, ITS OFFICERS, DIRECTORS OR EMPLOYEES, TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE AMOUNT OF MONEY YOU TRANSFERRED TO Urala Communications IN RELATION TO THE TRANSACTION GIVING RISE TO SUCH LIABILITY.</p>
        <p>&nbsp;</p>
        <h3>Notice to Apple App Users</h3>
        <p>To the extent You are using the App on an iOS device, You acknowledge that these Terms and Conditions form an agreement between You and the Company, not with Apple Inc. (“ <span class="bold"> Apple </span> ”), and that Apple is not responsible for the Services or the content thereof. Apple has no obligation to furnish any maintenance and support services with respect to the Services. If the Services fails to conform to any applicable warranty, You may notify Apple and Apple will refund any applicable purchase price for the mobile application to you; and, to the maximum extent permitted by applicable law, Apple has no other warranty obligation with respect to the Services. Apple is not responsible for addressing any claims by You or any third-party relating to the Services or your possession and/or use of the Services, including: (a) product liability claims; (b) any claim that the Services fails to conform to any applicable legal or regulatory requirement; or (c) claims arising under consumer protection or similar legislation. Apple is not responsible for the investigation, defense, settlement and discharge of any third-party claim that the Services and/or your possession and use of the Services infringe a third-party’s intellectual property rights. You agree to comply with any applicable third-party terms when using the Services. Apple and Apple’s subsidiaries are third-party beneficiaries of these Terms and Conditions, and upon your acceptance these Terms and Conditions, Apple will have the right (and will be deemed to have accepted the right) to enforce them against You as a third-party beneficiary. You hereby represent and warrant that: (i) You are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) You are not listed on any U.S. Government list of prohibited or restricted parties.</p>
        <p>In-App Purchases:</p>
        <ol>
        <li>When You make an In-App Purchase, payment will be charged to your Apple account at confirmation of the purchase.</li>
        <li>In-App Purchases may take the form of a subscription. Any unused portion of a free trial period (if offered) will be forfeited when You purchase a subscription (where applicable).</li>
        <li>In-App Purchases may take the form of an auto-renewable subscription. These subscriptions automatically renew unless auto-renew is turned off at least 24-hours before the end of the current subscription period. Your Apple account will be charged for renewal within 24-hours prior to the end of the current subscription period. You may manage the subscriptions and turn off auto-renewal by going to your Apple account settings after purchase.</li>
        </ol>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Market Information</h3>
        <p>Urala Communications may make available to you through one or more of its Services a broad range of financial information that is generated internally or obtained from agents, vendors or partners (“ <span class="bold"> Third Party Providers </span> ”). This includes, but is not limited to, financial market data, quotes, news, analyst opinions, research reports, graphs and data (“ <span class="bold"> Market Information </span> ”).</p>
        <p>Market Information provided on the Services is not intended as investment advice. Urala Communications does not endorse or approve the Market Information, and we make it available to you only as a service for your own convenience. Urala Communications and its Third Party Providers do not guarantee the accuracy, timeliness, completeness or correct sequencing of the Market Information, or warrant any results from your use or reliance on the Market Information.</p>
        <p>Market Information may quickly become unreliable for various reasons including, for example, changes in market conditions or economic circumstances. Neither Urala Communications nor the Third Party Providers are obligated to update any information or opinions contained in any Market Information, and we may discontinue offering Market Information at any time without notice. You agree that neither Urala Communications nor the Third Party Providers will be liable in any way for the termination, interruption, delay or inaccuracy of any Market Information. You will not “deep-link”, redistribute or facilitate the redistribution of Market Information, nor will you provide access to Market Information to anyone who is not authorized by Urala Communications to receive Market Information.</p>
        <p>With regard to any Market Information displayed on the Services, you are prohibited from, and hereby represent and warrant that you shall not: (i) copy, store, sell, license, distribute, transmit or duplicate to any third party or to any person any Market Information or any part thereof in any form or by any means; (ii) make the Market Information available on any website or in an application, or available to the public via the internet or otherwise; (iii) use the Market Information for the purpose of creating and/or operating (directly or by any third party) any financial product, index or service, or in any other manner without Urala Communications or its applicable Third Party Providers' permission; (iv) use the trademarks, logos, brand names or any other similar identifying mark, or remove any copyright or proprietary notices incorporated into the Market Information (“Marks”) and you hereby acknowledge that Urala Communications or its applicable Third Party Providers are the owners of the intellectual property rights in, and relating to, the Market Information any Marks; (v) use the Market Information in any way or for any purpose that would require a separate license from Urala Communications or its applicable Third Party Providers or any other person; and (vi) permit, or purport to permit, any third party to do any of the foregoing.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Use &amp; Access</h3>
        <p>You shall be responsible for providing and maintaining the means by which you access the Services, which may include, but is not limited to, your personal computer or mobile device, connectivity hardware, and telecommunication lines.</p>
        <p>You shall be responsible for all access and service fees necessary to connect to the Services and assume all charges incurred by use of such connectivity services. You further assume all risks associated with the use and storage of information on your personal computer, mobile device or on any other computer or device through which you will gain access to the Services (hereinafter referred to as “ <span class="bold"> Computer </span> ”).</p>
        <p>You represent and warrant that you have implemented and plan to operate and maintain appropriate protection in relation to the security and control of your Computer and any information and data included therein.</p>
        <p>You agree that Urala Communications will not be liable in any way to you in the event of failure of or damage or destruction to your Computer systems, data or records or any part thereof, or for delays, losses, errors or omissions resulting from the failure or mismanagement of any telecommunications or Computer equipment or software.</p>
        <p>You will not in any way, whether directly or indirectly, expose Urala Communications or any of Urala Communications's online service providers to any computer virus or other similarly harmful or inappropriate material or device.</p>
        <p>Without limiting the generality of the foregoing, your use of the Services is subject to the following restrictions:</p>
        <ol>
        <li>You may not use, sell, rent, lease, copy, modify, distribute, redistribute, license, publicly perform or display, publish, edit, create derivative works from, or otherwise make unauthorized use of the Services and/or any Content and Marks, without Urala Communications's prior explicit written consent; Likewise, You shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Services, without Urala Communications's prior explicit written consent;</li>
        <li>Except as expressly stated herein, no part of the Services, Content and/or Marks contained therein may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means, without Urala Communications's prior explicit written consent;</li>
        <li>You shall not access the Services in order to build a similar or competitive service;</li>
        <li>You may not use the Services in connection with material which promotes illegal activities, or the violation of any local, state, national, or international law or regulation, including, without limitation, laws governing intellectual property and other proprietary rights (including, but not limited to, patents, trademarks, trade secrets, copyrights, or any confidential, proprietary or trade secret information of any third party), information protection and privacy, including, but not limited to, content which disseminates another person's personal information without his or her permission;</li>
        <li>The Services may not be used or accessed by any automated machine, bot, spider, or such other automated feature or service;</li>
        <li>You shall not impersonate any person or entity or otherwise misrepresent affiliation, connection or association with any person or entity, or use any fraudulent, misleading or inaccurate contact information;</li>
        <li>You may not remove, circumvent, disable, damage or otherwise interfere with any features of the Services, or attempt to gain unauthorized access to any portion thereof through any means, or interfere with, corrupt, or disrupt the operation or performance of the Services or the ability of any other person to use them (including, without limitation, by attempting to degrade the performance of the servers in any way);</li>
        <li>You may not violate other users' or third parties' rights to privacy, publicity and other rights, or harvest, scrape, data aggregate, data mine, screen scrape, index or collect data and information about other users or third parties without their consent, whether manually, or automatically with the use of any means, including without limitation bots, crawlers, spiders, sifters and load testers, without the express written consent of Urala Communications, or engage in testing, pen-testing, sniffing or monitoring of the Services, their systems, software or hardware in any way;</li>
        <li>You may not use the Services in connection with material which a reasonable person could deem to be: offensive, inaccurate, incomplete, abusive, obscene, objectionable, defamatory, libelous, fraudulent or deceptive, indecent, pornographic, profane, threatening, advocating harassment or intimidation, distressing, vulgar, hateful, malicious, harmful for minors, racially or ethnically offensive, advocating racism, bigotry, hatred or physical harm of any kind against any group or individual, or disparaging the religious, political, or legal agenda of any person or entity, or is otherwise inconsistent with these Terms and Conditions including any of our policies;</li>
        </ol>
        <p>Urala Communications reserves the right, at any time, to modify, suspend, or discontinue the Services or any part thereof with or without notice. You agree that Urala Communications will not be liable to You or to any third party for any modification, suspension, or discontinuance of the Services or any part thereof.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Company's Rights</h3>
        <p>Urala Communications reserves the right to suspend the operation of the Services or any part or sections thereof at any time and no claims may be entertained against the Company in connection thereto.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Force Majeure</h3>
        <p>You agree that Urala Communications will not be liable in any way to you or to any other person in the event of force majeure (including, but not limited to, the act of any government or legal authority) or for the failure of or damage or destruction to your computer systems, data or records or any part thereof, or for delays, losses, errors or omissions resulting from the failure or mismanagement of any telecommunications or computer equipment or software.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Technical Problems</h3>
        <p>You understand that while the Internet and the World Wide Web are generally reliable, technical problems or other conditions may delay or prevent you from accessing the Services.</p>
        <p>Urala Communications shall not be liable, and you agree not to hold or seek to hold Urala Communications or any of its agents or service providers liable, for any technical problems, system failures and malfunctions, communication line failures, equipment or software failures or malfunctions, system access issues, system capacity issues, high Internet traffic demand, security breaches and unauthorized access, and other similar computer problems and defects.</p>
        <p>Urala Communications does not represent, warrant or guarantee that you will be able to access or use the Services at times or locations of your choosing, or that Urala Communications will have adequate capacity for the Services as a whole or in any geographic location.</p>
        <p>Urala Communications does not represent, warrant or guarantee that the Services will provide uninterrupted and error-free service. Urala Communications does not make any warranties or guarantees with respect to the Services and the Content, including but not limited to, warranties for merchantability or fitness for a particular purpose.</p>
        <p>Without limiting the foregoing Urala Communications will not be responsible for an impossibility to execute orders and requirements due to failures in the operation of informational systems caused by technical faults, which are beyond its control.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>User Content</h3>
        <p>“User Content” means any and all information and content that You submit to, or use with, the Services (e.g., Your comments on articles). You are solely responsible for Your User Content. You assume all risks associated with the use of Your User Content, including any reliance on its accuracy, completeness or usefulness by others, or any disclosure of Your User Content that makes You or any third party personally identifiable.</p>
        <p>You hereby represent and warrant that: (a) You are the owner of the User Content, or have sufficient rights and authority thereto; and (b) Your User Content does not violate these Terms and Conditions; and (c) your User Content does not contain any virus, adware, spyware, worms, or other harmful or malicious code. You alone are responsible for Your User Content.</p>
        <p>Urala Communications is not obligated to backup any User Content and User Content may be deleted at any time. You are solely responsible for creating backup copies of Your User Content.</p>
        <p>By posting or uploading User Content to the Services, You hereby grant, and You represent and warrant that You have the right to grant, to Urala Communications an irrevocable, nonexclusive, royalty-free and fully paid, worldwide license to reproduce, distribute, publicly display and perform, prepare derivative works of, incorporate into other works, and otherwise use Your User Content, and to grant sublicenses of the foregoing. You agree to irrevocably waive (and cause to be waived) any claims and assertions of moral rights or attribution with respect to User Content.</p>
        <p>If You provide Urala Communications any feedback or suggestions regarding the Services (“Feedback”), You hereby assign to Urala Communications all rights in the Feedback and agree that Urala Communications shall have the right to use such Feedback and related information in any manner it deems appropriate. Urala Communications will treat any Feedback You provide to Company as non-confidential and non-proprietary. You agree that You will not submit to Urala Communications any information or ideas that You consider to be confidential or proprietary.</p>
        <p>Urala Communications reserves the right (but have no obligation, except as and to the extent required by applicable law) to review any User Content, investigate, and/or take appropriate action against You in its sole discretion (including removing or modifying Your User Content, terminating Your account, and/or reporting You to law enforcement authorities).</p>
        <p>Each Services user is solely responsible for any and all of its User Content. Urala Communications does not control User Content, nor shall Urala Communications be responsible for any User Content. Urala Communications makes no guarantees regarding the accuracy, currency, suitability, or quality of any User Content. Your interactions with other Services users are solely between You and such user. You agree that Urala Communications will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between You and any user, Urala Communications is under no obligation to become involved in its resolution or in any other manner whatsoever.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Trademarks and Copyrights</h3>
        <p>All rights, titles and interests in and to the Services, the Content, the Marks, including but not limited to the the-markets.com” and “Urala Communications” trademarks, services marks, trade names, and logos are owned by Urala Communications, or its affiliates, or other licensors and are protected by copyright and trademark laws, and international treaties.</p>
        <p>You agree not to delete any copyright notices or other indications of protected intellectual property rights from materials that you print or download from the Services. You will not obtain any intellectual property rights or any right or license to use such materials or the Services, other than as expressly set out in these Terms and Conditions.</p>
        <p>Images displayed on the Services are either the property of Urala Communications or its licensors. You agree not to upload, post, reproduce or distribute any information, software or other material protected by copyright or any other intellectual property right (as well as rights of publicity and privacy) without first obtaining the permission of the owner of such rights and the prior written consent of Urala Communications.</p>
        <p>Nothing contained on the Services may be construed as granting, by implication, estoppels, or otherwise, any license or right to use any trademark without the written permission of Urala Communications or any third party that may own the trademarks. Your use of trademarks, or any other content of the Services, except as provided herein, is strictly prohibited.</p>
        <p>If You believe that one of our users, or Services, is unlawfully infringing the copyright(s) in a copyrighted material, and wish to have the allegedly infringing material removed, the following information in the form of a written notification (pursuant to 17 U.S.C. § 512(c)) must be provided to our designated Copyright Agent:</p>
        <ol>
        <li>Your physical or electronic signature;</li>
        <li>Identification of the copyrighted work(s) that You claim to have been infringed;</li>
        <li>Identification of the material on our services that You claim is infringing and that You request us to remove;</li>
        <li>Sufficient information to permit us to locate such material;</li>
        <li>Your address, telephone number, and e-mail address;</li>
        <li>A statement that You have a good faith belief that use of the objectionable material is not authorized by the copyright owner, its agent, or under the law; and</li>
        <li>a statement that the information in the notification is accurate, and under penalty of perjury, that You are either the owner of the copyright that has allegedly been infringed or that You are authorized to act on behalf of the copyright owner.</li>
        </ol>
        <p>Please note that, pursuant to 17 U.S.C. § 512(f), any misrepresentation of material fact in a written notification automatically subjects the complaining party to liability for any damages, costs and attorney's fees incurred by us in connection with the written notification and allegation of copyright infringement.</p>
        <p>For any copyright related inquiries please contact us using the below details:</p>
        <p>Email:&nbsp;legal@the-markets.com</p>
        <p>Address: Urala Communications Ltd., 〒104-0032 Tokyo,<br>Chuo City,<br>Hatchobori, <br>1 Chome−5−2 はごろもビル2F</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Breach</h3>
        <p>You agree to fully indemnify, defend and hold harmless Urala Communications, its corporate affiliates and their respective officers, directors and employees immediately upon demand from and against all claims, demands, liabilities, damages, losses, costs and expenses, including legal fees and other charges whatsoever, howsoever caused, that may arise as a result of: (i) any breach of these Terms and Conditions by you or (ii) violation by you of any law or the rights of any third party.</p>
        <p>Without prejudice to any other rights in these Terms and Conditions, if You breach in whole or in part any provision contained herein, Urala Communications or any of its corporate affiliates which provide the Services to You reserve the right to take such action as they sees fit, including (but not limited to) terminating any agreement in place with You, terminating or blocking the Services to You and/or taking legal action against yYou.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Governing Law and Court Jurisdiction</h3>
        <p>These Terms and Conditions shall be governed by the laws of the British Virgin Islands (“BVI”), without regard to conflicts of law principles thereof. This is the case regardless of whether you reside or transact business with Urala Communications anywhere else in the world.</p>
        <p>If any part of these Terms and Conditions are held unlawful, void or unenforceable, that part will be deemed severable and will not affect the validity and enforceability of any remaining provisions.</p>
        <p><u> Exclusive Court Jurisdiction: </u> &nbsp;You agree to submit to the personal and exclusive jurisdiction of the courts located within the BVI to settle any dispute, which may arise in relation thereto.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Disclosures</h3>
        <p>The Services hereunder are offered by Urala Communications Limited, registered at:</p>
        <p>Urala Communications Ltd.,<br>3076 Sir Francis Drake's Highway,<br>P.O. Box 3463, Road Town,<br>Tortola,<br>British Virgin Islands</p>
        <p>It is important that You be fully aware of the following point: Using a high level of leverage to conduct foreign exchange transactions involves the risk that borrowing costs will be higher than the income which is derived from the assets.</p>
        <p>The result of the above is that even a slight fluctuation of the market could mean substantial gains when these fluctuations are in Your favor, but that could also mean considerable losses if the fluctuations are to Your detriment.</p>
        <p><span class="bold"> &nbsp; </span></p>
        <h3>Special Conditions Applicable to Tools</h3>
        <p>Urala Communications makes available to you certain trading and investment tools (the “ <span class="bold"> Tools </span> ”) which can be integrated within your website via the HTML code available from the “Tools” section of the Services (the “ <span class="bold"> Code </span> ”). These special conditions (the “ <span class="bold"> Special Conditions </span> ”) constitute a part of the Terms and Conditions and both are applicable to users who have integrated the Tools into their own websites. In the event of a conflict between a provision of these Special Conditions and any provision of the Terms and Conditions, then the Special Conditions shall prevail.</p>
        <p>Urala Communications does not and cannot guarantee or represent that any of the information and data made available via the Tools is real-time, accurate, complete, current or appropriate for your needs. Certain information and data made available via the Tools is obtained from Third Party Providers (defined above) who are generally understood to be sources of reliable information and data. However, due to a variety of different factors, including mechanical and human error, the timeliness, completeness, accuracy and correct sequencing of such information and data and results obtained from use thereof are not guaranteed by Urala Communications.</p>
        <p>ALL INFORMATION AND DATA MADE AVAILABLE VIA THE TOOLS IS PROVIDED ON AN “AS-IS” BASIS FOR INFORMATIONAL PURPOSES ONLY, AND IS NOT INTENDED FOR ACTUAL TRADING PURPOSES OR MARKET ADVICE.</p>
        <p>Urala Communications may integrate advertising and links to third party websites within the Tools but does not endorse such advertising or the content and services which are provided on third party websites accessible via the Tools. You will not modify, remove, change, edit, amend, alter, cover, hide, block, obscure, bypass or reorder any aspect of the advertising and links which are referred to above.</p>
        <p>You will not be entitled to any compensation in connection with the integration of the advertisement within the Tools.</p>
        <p>Urala Communications and its employees, officers, directors, affiliates, agents or licensors will not be liable to you or any third party for any financial loss, lost profits, any special, incidental or consequential damage or any other similar damage or any other loss or injury, incurred as a result of delays, informational errors, inaccuracy or incompleteness of the information and data provided in the Tools or any actions taken in reliance thereon, or for the advertising or content and services which are provided on third party websites accessible via the Tools.</p>
        <p>Subject to the terms and conditions set forth herein, Urala Communications grants you a non-exclusive, non-transferable and limited license to access and use the Tools solely for your personal, non-commercial use (the “ <span class="bold"> Tools License </span> ”). If you are using the Tools for commercial purposes, Urala Communications grants you a non-exclusive, non-transferable, limited license, for a trial period of one (1) month only to access and use the Tools (the “ <span class="bold"> Trial License </span> ”) (the “ <span class="bold"> Tools License </span> ” together with the “ <span class="bold"> Trial License </span> ” are hereinafter referred to as the “ <span class="bold"> Licenses </span> ”). After the Trial License expires, you agree to enter into a separate agreement with Urala Communications in order to continue using the Tools. Urala Communications has sole discretion in deciding whether your use of the Tools is commercial or non-commercial.</p>
        <p>The Licenses are conditional on your full and continued compliance with these Terms and Conditions (including the Special Conditions). You agree not to resell or permit access to the Tools to others, and not to copy any materials appearing on the Tools for resale to others or for any other purpose without the prior consent of Urala Communications. You agree not to use the Tools for any unlawful purpose. The Licenses will terminate if you fail to comply with any term or condition of these Terms and Conditions (including the Special Conditions). Upon such violation, you agree to cease making use of the Tools. You agree that Urala Communications, at its sole discretion and with or without notice, may terminate your access to any or all Tools, and remove and discard any information or content within the Tools at any time, including during the Trial License.</p>
        <p>Notwithstanding the grant of the Licenses, you agree and acknowledge that all right, title and interest in and to the Tools, the Code and all information and data made available therein including (but not limited to) trademarks, signs, trade names, domain names, images, pictures, graphics, photographs, animations, videos, music, audio and text belong to Urala Communications, its affiliates and/or the Third Party Providers (as applicable) and are protected by copyright and/or other intellectual property rights and/or other rights.</p>
        <p>You are not permitted to make any alterations whatsoever to the Code including (but not limited to) alterations which hide or obscure advertising and links to Urala Communications or third party websites accessible via the Tools. You may not circumvent any mechanism included in the Code and/or Tools for preventing unauthorized reproduction or distribution. Without prejudice to any other right, Urala Communications is entitled to immediately block use of the Tools on your website in the event that you breach these provisions.</p>
        <p>You will post to your website an appropriate privacy policy containing notice of the cookies used within the Tools, abide by the terms of such a privacy policy and comply with any and all applicable laws and regulations relating to the collection of information from visitors to your website on which Tools are being utilized.</p>
        <p>Nothing in these Terms and Condition will create any obligation on Urala Communications to pursue or consummate any business or other relationship with you.</p>
        <h3>Miscellaneous</h3>
        <p>Urala Communications may assign its rights in the Services to any third party at its sole discretion. You may not assign or delegate your rights according to this Agreement, without the Company's prior written consent.</p>
        <p>Failure to assert, at any time, any right, or require performance with regard to these Terms and Conditions by or on behalf of Urala Communications shall not constitute concession, yield, waiver or relinquishment of any sort, and shall not limit Urala Communications's rights with respect to such breach or any subsequent or other breaches.</p>
        <p>Urala Communications reserves the right, at its sole discretion, to periodically amend or revise these Terms and Conditions. Your continued use of the Services, following such amendment, constitutes your acknowledgement and consent of such amendments. The last revision will be reflected in the “Last revised” heading above.</p>
      </div>
    </div>
  </div>
</template>

<script>
  export default { }

</script>

<style lang="scss" scoped>
    p {
        margin-bottom: 0.3rem;
    }
    hr {
        border-top: 1px solid rgb(198 198 198 / 41%);
        display: block;
        width: 100%;
    }
    h3{
      margin-top: 2rem;
    }
</style>
